name: Auto Merge Pull Request

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  merge:
    if: github.event.pull_request.head.ref == 'arvind-desktop' || github.event.pull_request.head.ref == 'arvind-laptop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Auto Merge Pull Request
        run: |
          git checkout main
          git merge --no-ff origin/${{ github.event.pull_request.head.ref }}
          git push origin main
